name: Release Coin Price
on:
  push:
    branches:
      - main

    paths-ignore:
      - 'README.md'
      - '.github/workflows/**'
      - 'img/**'


jobs:
  release:
    name: Generate Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1 
        id: tag_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          TAG_PREFIX: v
          PRERELEASE: true

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: ${{ steps.tag_version.outputs.new_tag }}
          draft: false
          prerelease: false
